"""
3D Human Anatomy Explorer API
-----------------------------
Backs the interactive anatomy viewer shown on the Doctor, Patient and Caregiver pages.

  GET  /api/anatomy/systems                    -> taxonomy used by the viewer (skeletal, muscular, nervous, ...)
  GET  /api/anatomy/status                     -> which LLM tier will answer (MedGemma / Gemini / Groq / offline)
  POST /api/patients/{patient_id}/anatomy/explain
                                               -> patient-grounded explanation for a selected system / structure

Explanations are generated by MedGemma 1.5 when a MEDGEMMA_BASE_URL endpoint is
configured, otherwise the existing Gemini -> Groq -> offline cascade is used.
Nothing is written to the clinical record: this is a read-only, audited feature.
"""
import logging
import uuid
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, Request
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.dependencies import get_current_user, verify_patient_access
from app.models.security import User
from app.services.audit_service import AuditService
from app.services.clinical_context_service import ClinicalContextService
from app.services.llm.resilient_provider import ResilientLLMProvider
from app.services.llm.medgemma_provider import (
    ANATOMY_SYSTEMS,
    ANATOMY_AUDIENCES,
    MedGemmaProvider,
    detect_anatomy_system,
)

logger = logging.getLogger(__name__)

router = APIRouter(tags=["3D Human Anatomy"])

DISCLAIMER = (
    "Educational anatomy information generated from the patient's EvoCare record. "
    "It is not a diagnosis, does not replace clinical judgement, and does not alter treatment."
)


class AnatomySystemOut(BaseModel):
    key: str
    label: str
    description: str
    evocare_domains: List[str]


class AnatomyExplainRequest(BaseModel):
    system: Optional[str] = Field(None, description="One of the anatomy system keys, e.g. 'skeletal'. Auto-detected from question if omitted.")
    structure: Optional[str] = Field(None, max_length=120, description="Optional specific structure clicked in the viewer, e.g. 'left knee'.")
    question: Optional[str] = Field(None, max_length=1000)
    audience: Optional[str] = Field(None, description="doctor | patient | caregiver (defaults to the caller's role)")


class AnatomyExplainResponse(BaseModel):
    patient_code: str
    patient_name: str
    system: str
    system_label: str
    structure: Optional[str] = None
    audience: str
    question: Optional[str] = None
    explanation: str
    model_used: str
    tier: str
    from_cache: bool = False
    fallback_notice: Optional[str] = None
    related_evidence: List[Dict[str, Any]] = []
    disclaimer: str = DISCLAIMER


@router.get("/anatomy/systems", response_model=List[AnatomySystemOut])
def list_anatomy_systems():
    return [
        AnatomySystemOut(key=k, label=v["label"], description=v["description"], evocare_domains=v["evocare_domains"])
        for k, v in ANATOMY_SYSTEMS.items()
    ]


@router.get("/anatomy/status")
def anatomy_llm_status(current_user: User = Depends(get_current_user)):
    provider = ResilientLLMProvider()
    medgemma = provider.medgemma.status()
    if medgemma["configured"]:
        active = f"MedGemma 1.5 ({medgemma['model']})"
    elif provider.gemini.is_configured():
        active = f"Google Gemini Flash ({provider.gemini.model})"
    elif provider.groq.is_configured():
        active = f"Groq ({provider.groq.primary_model})"
    else:
        active = "EvoCare Offline Anatomy Engine"
    return {"medgemma": medgemma, "active_tier": active}


@router.post("/patients/{patient_id}/anatomy/explain", response_model=AnatomyExplainResponse)
def explain_anatomy(
    patient_id: str,
    body: AnatomyExplainRequest,
    request: Request,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    patient = verify_patient_access(patient_id, current_user, db, request)

    role_str = current_user.role.value if hasattr(current_user.role, "value") else str(current_user.role)
    audience = (body.audience or role_str or "patient").lower()
    if audience not in ANATOMY_AUDIENCES:
        audience = "doctor" if audience == "admin" else "patient"

    system_key = (body.system or "").lower().strip()
    if system_key not in ANATOMY_SYSTEMS:
        system_key = detect_anatomy_system(f"{body.question or ''} {body.structure or ''}") or "skeletal"

    seed_question = body.question or f"{ANATOMY_SYSTEMS[system_key]['label']} {' '.join(ANATOMY_SYSTEMS[system_key]['keywords'][:4])}"
    try:
        context = ClinicalContextService.build_patient_context(db, patient.patient_code, seed_question)
    except Exception as e:
        logger.error(f"Anatomy: failed to build patient context: {e}")
        context = {"patient": {"patient_code": patient.patient_code, "name": patient.name, "age": patient.age, "sex": patient.sex}}

    provider = ResilientLLMProvider()
    result = provider.explain_anatomy(system_key, audience, context, body.question, body.structure)

    # Surface record items related to this system so the UI can link evidence codes
    kws = ANATOMY_SYSTEMS[system_key]["keywords"]
    related: List[Dict[str, Any]] = []
    for m in context.get("medications", []) or []:
        if isinstance(m, dict) and any(k in f"{m.get('name','')} {m.get('indication','')}".lower() for k in kws):
            related.append({"type": "MEDICATION", "label": f"{m.get('name')} {m.get('dose','')}", "evidence_code": m.get("evidence_code")})
    for o in context.get("caregiver_observations", []) or []:
        if isinstance(o, dict) and any(k in (o.get("observation_text") or "").lower() for k in kws):
            related.append({"type": "CAREGIVER", "label": (o.get("observation_text") or "")[:100], "evidence_code": o.get("evidence_code")})
    for c in context.get("memory_claims", []) or []:
        if isinstance(c, dict) and any(k in (c.get("statement") or "").lower() for k in kws):
            related.append({"type": "MEMORY", "label": (c.get("statement") or "")[:100], "evidence_code": (c.get("citations") or [None])[0]})

    ip = request.client.host if request.client else "unknown"
    AuditService.log_audit_event(
        db=db,
        action="ANATOMY_EXPLAIN",
        user_id=current_user.id,
        username=current_user.username,
        role=role_str,
        patient_id=patient.patient_code,
        resource_type="ANATOMY_EXPLORER",
        resource_id=f"ANAT-{uuid.uuid4().hex[:6].upper()}",
        result="SUCCESS",
        details={"system": system_key, "structure": body.structure, "audience": audience, "tier": result.get("tier")},
        ip_address=ip,
    )

    return AnatomyExplainResponse(
        patient_code=patient.patient_code,
        patient_name=patient.name,
        system=system_key,
        system_label=ANATOMY_SYSTEMS[system_key]["label"],
        structure=body.structure,
        audience=audience,
        question=body.question,
        explanation=result["text"],
        model_used=result.get("model_used", "unknown"),
        tier=result.get("tier", "offline"),
        from_cache=bool(result.get("from_cache")),
        fallback_notice=result.get("fallback_notice"),
        related_evidence=related[:10],
    )
